name: Generate Snake Animation

on:
  # Trigger the action on push or once a day
  push:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Run the snake animation generator
      - uses: Platane/snk@v3
        with:
          github_user_name: FernandoR7
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Upload the generated files to the GitHub repository
      - name: Upload GitHub Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist/*
